//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Nota.cpp
//  @ Date : 28/10/2012
//  @ Author : 
//
//


#include "Nota.h"

int Nota::getNota(int ID) {

}

int Nota::getProductos(int ID) {

}

